### PR TITLE
Background animation

### LINKED ISSUE #3: Add background with CSS animations
**Is your feature request related to a problem? Please describe.**
The background now applied looks so dull, change it and add CSS or JS animations to make it look better.

**Describe the solution you'd like**
just be creative as you like.

**Describe alternatives you've considered**
N/A

**Additional context**

### PR DESCRIPTION
**Pull request by ramdhanihendrie**
## What is the change?
Add background animation and change link button color

## Related issue?
closes: #3

### CODE REVIEW

**Comment by akashrchandran** [comment]
@ramdhanihendrie add a image/gif of the result.

**Comment by ramdhanihendrie** [comment]
this is the result
CPT2210031612-1366x616

**Review by akashrchandran — APPROVED** [review]
Looks good to me. Keep contributing 🥳.

**Comment by ramdhanihendrie** [comment]
And I think there is a typo in the repo label, there is a `hactoberfest`, it should be `hacktoberfest`

**Pull request merged**
